project:
  type: website

website:
  title: "IHMI"
  navbar:
    background: "#1E88E5"
    logo: assets/img/logo.jpg
    right:
      - href: "#"
        text: "<img src='/assets/img/dbt_logo.png' alt='DBT' class='right-logo'>"
    left:
      - href: pages/about.qmd
        text: About
      - href: pages/protocols.qmd 
        text: Protocols
      - href: pages/data.qmd
        text: Data
      - text: Team
        menu:
          - text: Partner Institutes
            href: pages/team/institutes.qmd
          - text: People
            href: pages/team/people.qmd
      - href: pages/gallery.qmd
        text: Gallery

  page-footer:
    center:
      - text: |
          <hr class="footer-line" />
          <div class="footer-logos">
            <div class="footer-partners">
              <p style="align:centre">Department of Biotechnology, Ministry of Science and Technology, Government of India. Sanction Order No.: BT/PR23968/BRB/10/1602/2017 dated 9th March 2020</p>
              <h3>Partners</h3>
              <div class="logo-row">
                <img src="/assets/img/nccs_logo.png" alt="partner 1">
                <img src="/assets/img/aiims_logo.png" alt="partner 2">
                <img src="/assets/img/ibsd_logo.png" alt="partner 3">
                <img src="/assets/img/kem_logo.jpg" alt="partner 4">
                <img src="/assets/img/sppu_logo.png" alt="partner 5">
                <img src="/assets/img/tdu_logo.png" alt="partner 6">
                <img src="/assets/img/srm_logo.png" alt="partner 7">
              </div>
            </div>
          </div>

format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 1.5rem
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">

editor: visual

