---
title: ""
format:
  html:
    page-layout: full
---

## Scientific Coordinator

-   **Dr. Suchita Ninawe**,Senior Adviser and Scientist H, Department of Biotechnology

## DBT Administrative Scientist

-   **Dr. Richi V. Mahajan**, Scientist D, Department of Biotechnology

## Investigators

```{r}
#| message: true
#| warning: true
#| echo: false

library(DT)
df <- read.table(file = './investigators.csv',header = T,sep = ',')

df$Name <- paste0("<a href='", df$URL, "'>",df$Name,"</a>")
df$URL <- NULL
DT::datatable(
  df, escape = FALSE, options = list(
    searching = FALSE, paging = FALSE, info = FALSE
  )
)
```

## Working groups

| Group | Members |
|------------------------------------|------------------------------------|
| Conceptualization and project writing | Abhijit Kulkarni, Dhiraj Dhotre, Sanjay Juvekar, Shantanu Ozarkar, Shreyas Kumbhare, Vilas Sinkar, Yogesh Shouche |
| Project coordination and administration group | Anand Krishnan, Balakrishnan S Ramakrishna, Dhiraj Agarwal, Dhiraj Dhotre, Girish Tillu, Govind Makharia, Indira Devi Sarangthem, John P Mechenro, Mahima Gubani, Omkar Godse, Sanjay Juvekar, Shantanu Ozarkar, Simmy Frankenstein, Subrahmanya Kumar Kukkupuni, Varun Shah, Vineet Ahuja, Yogesh Shouche |
| Ayurvedic Prakriti Assessment | Sanket V Sharma, Sumit Salunke, Venkatesh Shankar Anthropological Assessment: Akanksha Choudhari, Chaitali Choudhari, Gauri Bhide, John P Mechenro, L. Mohindro Singh, Mahima Gulbani, Ng. Ngashangva, Simmy Frankenstein, Vivek Pakhare, Y. Randhir Babu Singh |
| Sampling group | Aditi Deshpande, Akanksha Choudhari, Ashwini Hagir, Chaitali Choudhari, Gauri Bhide, John P Mechenro, L. Mohindro Singh, Mahima Gulbani, Mitali Inamdar, Mohak Gujare, Ng. Ngashangva, Omkar Godse, Sanket V Sharma, Shubham Gurav, Simmy Frankenstein, Sumit Salunke, Swapnil Bodkhe, Venkatesh Shankar, Vivek Pakhare, Y. Randhir Babu Singh |
| Microbial Isolation Group | Ashwini Hagir, Mitali Inamdar, Namrata Jiya |
| NGS Sequencing Group | Abhishek Gupta, Aditi Deshpande, Arinjay Gire, Ashwini Hagir, Mitali Inamdar, Mohak Gujare, Namrata Jiya, Shivang Bhanushali, Shubham Gurav, Swapnil Bodkhe |
| Data Curation Group | Aditi Deshpande, Arinjay Gire, Chaitali Choudhari, Dhiraj Agarwal, Dhiraj Dhotre, Himangi Lubree, Mitali Inamdar, Prajakta Pakhale, Shantanu Ozarkar, Sonam Malik, Sukanya Dange, Varun Shah |
| Data Analysis Group | Abhishek Gupta, Dattatray Mongad, Dhiraj Dhotre, Mitali Inamdar |
| Biobanking Group | Aditi Deshpande, Arinjay Gire, John P Mechenro, Mitali Inamdar, Varun Shah |

