---
title: "About"
format: 
  html: 
    toc: true
---

::: {#about style="text-align: justify"}
India’s extraordinary mosaic of cuisines, climates, genetic backgrounds, and cultural traditions provides a rare window into human–microbe co-evolution. Yet, despite comprising nearly one-sixth of the global population, Indian communities remain vastly underrepresented in existing microbiome research.

IHMI confronts this disparity by establishing the first comprehensive microbial reference for the Indian population. This baseline not only deepens our understanding of population-specific microbiome patterns but also unlocks new opportunities for personalized health strategies grounded in indigenous biological and cultural contexts.
:::

### Vision

::: {#vision style="text-align: justify"}
To position India at the forefront of global microbiome science by unveiling its unique microbial heritage and enabling transformative advances in personalized nutrition, preventive health, and microbiome therapeutics rooted in the country's unparalleled genetic, cultural, and ecological diversity.
:::

### Mission

::: {#mission style="text-align: justify"}
To comprehensively map and characterize the diverse gut microbiome of Indian endogamous and tribal populations through a multidisciplinary, culturally contextualized, and scientifically rigorous approach. IHMI aims to establish a national microbiome reference that integrates dietary, ecological, genomic, metagenomic and Ayurvedic knowledge to empower precision healthcare and microbiome-based innovations tailored to the Indian population.
:::

### Need for mapping Indian Microbiome

::: {#need style="text-align: justify"}
-   India has huge diet, lifestyle and ethnic diversity and thus is a perfect model to study association of ‘Genetics, biogeography, lifestyle, ethnicity and diet with Microbiome’.

-   Increasing the success of FMT in Indian patients

-   Microbiota based metabolic disease models developed in one location fail in other location and hence cannot be extrapolated (He et al., 2018).

-   Correlating ‘-omics’ based gut microbiome concepts with traditional Indian Ayurvedic concepts.

-   Characterization of microbiome from autochthonous tribal populations which are not influenced by modernization and changing lifestyle may lead to identification of many unique and novel microbes.

-   Does Indian population have a new enterotype?
:::

### Key Gaps/Questions

::: {#gaps style="text-align: justify"}
-   Determining the baseline gut microbiome data of Indian endogamous groups having unparalleled varied dietary and lifestyle patterns.

-   What are the unique features of microbiota of Indian population? Is it possible to define the core Indian microbiome or their will be several core Indian Microbiome(s) ?

-   How microbiota changes across the population of India including tribal population living in their natural habitat and following traditional practices?

-   How does the diet, lifestyle and age influence the gut microbial community composition and structure?

-   Is there any association between microbiome and three distinct Ayurvedic Prakriti types?

-   Understanding the temporal variations in gut microbiome.
:::
